AWSTemplateFormatVersion: '2010-09-09'
Description: Setup S3 bucket for app-shopping-shell with CORS, website configuration, and public read access, including bucket policy.

Parameters:
  BucketName:
    Type: String
    Description: Bucket name for shopping-shell app

Resources:
  AppShellBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
  AppShellPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AppShellBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${BucketName}/*' 