AWSTemplateFormatVersion: '2010-09-09'
Description: Setup S3 bucket for app-shop with CORS and public read access, including bucket policy.

Parameters:
  BucketName:
    Type: String
    Description: Bucket name for shop app
  ShellAppBucketUrl:
    Type: String
    Description: Shell app origin

Resources:
  AppShopBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - !Ref ShellAppBucketUrl 
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  AppShopPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AppShopBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub 'arn:aws:s3:::${BucketName}/*'
